{{ define "library-helm-chart.externalSecret" }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-envs
  annotations:
    werf.io/weight: "-10"
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore  # or ClusterSecretStore

  # RefreshInterval is the amount of time before the values reading again from the SecretStore provider
  # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h" (from time.ParseDuration)
  # May be set to zero to fetch and create it once
  refreshInterval: "15s"

  target:
    name: {{ .Chart.Name }}-envs
  dataFrom:
  - extract:
      key: /k8s/services

{{- if eq .Chart.Name "alanbase-gate" }}
  - extract:
      key: /k8s/alanbase-gate
{{- end }}

{{- if .Values.accessTo }}

{{- if .Values.accessTo.postgresPool }}
  - extract:
      key: /k8s/postgres
  - extract:
      key: /k8s/postgres-pool-connect
{{- end }}

{{- if .Values.accessTo.postgresDB }}
  - extract:
      key: /k8s/postgres
  - extract:
      key: /k8s/postgres-db-connect
{{- end }}

{{- if .Values.accessTo.clickhouseStatistic }}
  - extract:
      key: /k8s/clickhouse-statistic
  - extract:
      key: /k8s/clickhouse
{{- end }}

{{- if .Values.accessTo.clickhouseLog }}
  - extract:
      key: /k8s/clickhouse-log
  - extract:
      key: /k8s/clickhouse
{{- end }}

{{- if .Values.accessTo.rabbitmq }}
  - extract:
      key: /k8s/rabbitmq
{{- end }}

{{- if .Values.accessTo.redis }}
  - extract:
      key: /k8s/redis
{{- end }}

{{- if .Values.accessTo.redisCommon }}
  - extract:
      key: /k8s/redis-common
{{- end }}

{{- if .Values.accessTo.redisRedirector }}
  - extract:
      key: /k8s/redis-redirector
{{- end }}

{{- if .Values.accessTo.redisPostbackProcessor }}
  - extract:
      key: /k8s/redis-postback-processor
{{- end }}

{{- if .Values.accessTo.mailgun }}
  - extract:
      key: /k8s/mailgun
{{- end }}

{{- if .Values.accessTo.postgresService }}
  - extract:
      key: /k8s/postgres-service
{{- end }}

{{- if .Values.accessTo.featureToggle }}
  - extract:
      key: /k8s/feature-toggle
{{- end }}

{{- if .Values.accessTo.importService }}
  - extract:
      key: /k8s/import-service
{{- end }}

{{- if .Values.accessTo.rates }}
  - extract:
      key: /k8s/rates
{{- end }}
{{- end }}

{{ end }}
