{{ define "library-helm-chart.externalSecret" }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-envs
  annotations:
    werf.io/weight: "-10"
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore  # or ClusterSecretStore

  # RefreshInterval is the amount of time before the values reading again from the SecretStore provider
  # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h" (from time.ParseDuration)
  # May be set to zero to fetch and create it once
  refreshInterval: "15s"

  target:
    name: {{ .Chart.Name }}-envs
  dataFrom:
  - extract:
      key: /k8s/services

{{- if .Values.accessTo }}

{{- if .Values.accessTo.postgresPool }}
  - extract:
      key: /k8s/postgres
  - extract:
      key: /k8s/postgres-pool-connect
{{- end }}

{{- if .Values.accessTo.postgresDB }}
  - extract:
      key: /k8s/postgres
  - extract:
      key: /k8s/postgres-db-connect
{{- end }}

{{- if .Values.accessTo.clickhouse }}
  - extract:
      key: /k8s/clickhouse
{{- end }}


{{- if .Values.accessTo.rabbitmq }}
  - extract:
      key: /k8s/rabbitmq
{{- end }}

{{- if .Values.accessTo.redis }}
  - extract:
      key: /k8s/redis
{{- end }}

{{- end }}

{{ end }}
