{{ define "library-helm-chart.serviceAccount" }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}

{{ end }}